# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oslab/sjoon/workspace/git/hartebeest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oslab/sjoon/workspace/git/hartebeest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oslab/sjoon/workspace/git/hartebeest/CMakeFiles /home/oslab/sjoon/workspace/git/hartebeest//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oslab/sjoon/workspace/git/hartebeest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named demo.run

# Build rule for target.
demo.run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo.run
.PHONY : demo.run

# fast build rule for target.
demo.run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.run.dir/build.make CMakeFiles/demo.run.dir/build
.PHONY : demo.run/fast

#=============================================================================
# Target rules for targets named libhartebeest

# Build rule for target.
libhartebeest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libhartebeest
.PHONY : libhartebeest

# fast build rule for target.
libhartebeest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libhartebeest.dir/build.make CMakeFiles/libhartebeest.dir/build
.PHONY : libhartebeest/fast

src/rdma-conf.o: src/rdma-conf.cpp.o
.PHONY : src/rdma-conf.o

# target to build an object file
src/rdma-conf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libhartebeest.dir/build.make CMakeFiles/libhartebeest.dir/src/rdma-conf.cpp.o
.PHONY : src/rdma-conf.cpp.o

src/rdma-conf.i: src/rdma-conf.cpp.i
.PHONY : src/rdma-conf.i

# target to preprocess a source file
src/rdma-conf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libhartebeest.dir/build.make CMakeFiles/libhartebeest.dir/src/rdma-conf.cpp.i
.PHONY : src/rdma-conf.cpp.i

src/rdma-conf.s: src/rdma-conf.cpp.s
.PHONY : src/rdma-conf.s

# target to generate assembly for a file
src/rdma-conf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libhartebeest.dir/build.make CMakeFiles/libhartebeest.dir/src/rdma-conf.cpp.s
.PHONY : src/rdma-conf.cpp.s

test/demo2.o: test/demo2.cpp.o
.PHONY : test/demo2.o

# target to build an object file
test/demo2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.run.dir/build.make CMakeFiles/demo.run.dir/test/demo2.cpp.o
.PHONY : test/demo2.cpp.o

test/demo2.i: test/demo2.cpp.i
.PHONY : test/demo2.i

# target to preprocess a source file
test/demo2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.run.dir/build.make CMakeFiles/demo.run.dir/test/demo2.cpp.i
.PHONY : test/demo2.cpp.i

test/demo2.s: test/demo2.cpp.s
.PHONY : test/demo2.s

# target to generate assembly for a file
test/demo2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.run.dir/build.make CMakeFiles/demo.run.dir/test/demo2.cpp.s
.PHONY : test/demo2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... demo.run"
	@echo "... libhartebeest"
	@echo "... src/rdma-conf.o"
	@echo "... src/rdma-conf.i"
	@echo "... src/rdma-conf.s"
	@echo "... test/demo2.o"
	@echo "... test/demo2.i"
	@echo "... test/demo2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

